### ISSUE TITLE
New function for email config

### ISSUE THREAD

**Issue by hanh45** [jcppkkk/redmine_mail_reminder#33]
Hello master,
After install this plugin, i see the plugin focus on projects.
Ex: I am manager of 10 projects, i will config 10 query for 10 projects.
The day i 'll receipt 10 email for 10 projects. 
Too much for the config.

I hope you develop function config focus on user:
From user => select group of user => select projects of user => select issues => check config => send one email.

Sorry for my english.

**Comment by hanh45** [comment]
Sorry because i don't read all issue.
The idea same: https://github.com/Hopebaytech/redmine_mail_reminder/issues/29
The function same: https://github.com/f0y/due_date_reminder

**Comment by jcppkkk** [comment]
Hi @hanh45 , for now there is a workaround. That is to set all 10 projects as subproject of a parent project, and  setup 1 query and 1 reminder for parent project. The result will like screenshot ![](https://lh3.googleusercontent.com/-A-s0giWSvvk/VNiFf7PnSfI/AAAAAAAACHI/6DA5JDDmF2U/s2048/2015-02-09%25252018_01_30-2015-02-09%25252017_52_56-Redmine%252520Issue%252520Reminder%252520-%252520jethro.yu%252540happygorgi.com%252520-%252520%2525E5%252592%25258C%2525E6%2525B2%25259B%2525E7%2525A7%252591%2525E6%25258A%252580%2525E8%252582%2525A1%2525E4%2525BB%2525BD%2525E6%25259C%252589%2525E9%252599%252590.png)

Global Reminder may be added in months or sooner if i have time to write this feature.

P.S. Custom query can be set as global query and be used in all projects / reminders. There is no need to create duplicate queries for projects if they are same query

**Comment by Androc** [comment]
>>> P.S. Custom query can be set as global query and be used in all projects / reminders. There is no need to create duplicate queries for projects if they are same query

That is what I wanted to say : usually your reminders are global, it is like "reminder users about issues that are opened since 7 days". This kind of query is not specific to a project.
Now I read again the #29, I think this is the same idea @dominch wanted to achieve.

**Comment by dominch** [comment]
I need to keep redmine installation as simple as possible. The idea is to send once a week list of issues to let know all users that have open issues by project and version, and priority. This plugin seems to be great but there should be option to set global notification and global query. In my case I don't want to show anything to users and let them decide what they will receive. They should get everything from every project when they should answer, close or re-assign issue. 

@hanh45 - I've tested this plugin but it sends emails only for issues that have due date, and that date is comming. It's good plugin but silent for everything without that date. I need something that will send reminder once a week from specified global query (for all projects).

**Comment by Androc** [comment]
@dominch, @hanh45 I have tested the solution proposed by @jcppkkk () that will certainly fit your needs and I explained it here : https://github.com/Hopebaytech/redmine_mail_reminder/issues/29#issuecomment-110616437

**Comment by dominch** [comment]
I can imagine that, but it's not good solution to rearrange project tree for any plugin. This way You will get extra clutter for every user. 
Is that really impossible to run reminders without specific project? You can view overall activity, queries across many projects etc. Why stick to project module only?

**Comment by Androc** [comment]
I am not the owner, nor good enough with Ruby to be able to judge if it is a trivial modifications, sorry.

**Comment by jcppkkk** [comment]
following up at #109
