### ISSUE TITLE
Page not reload after saving Issues Reminder

### ISSUE THREAD

**Issue by dondezo** [jcppkkk/redmine_mail_reminder#40]
Hi,
i have strage behevior after saving mail reminder page not reload and  after get this error:

Started PUT "/redmine/mail_reminders/7" for x.x.x.x at 2015-07-07 22:50:18 +0200
Processing by MailRemindersController#update as JS
  Parameters: {"utf8"=>"✓", "reminder"=>{"project_id"=>"82", "query_id"=>"102", "interval"=>"daily"}, "interval_value"=>"0", "administrator"=>"12", "commit"=>"Save", "id"=>"7"}
  Current user: admin (id=1)
Missing template, responding with 404
  Rendered common/error.html.erb (0.5ms)
Completed 404 Not Found in 40ms (Views: 1.3ms | ActiveRecord: 3.1ms)

chrome developer tools says in console:
POST https://xxxxxx.com/redmine/mail_reminders/7 404 (Not Found)m.ajaxTransport.send @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:4m.extend.ajax @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:4e.rails.n.ajax @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:21e.rails.n.handleRemote @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:21(anonymous function) @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:21m.event.dispatch @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:3m.event.add.r.handle @ jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js:3

**Comment by Androc** [comment]
Hello,

is it a new installation or after an update ?

If if is new, your plugin's directory should be redmine_mail_reminder and not mail_reminders.

**Comment by dondezo** [comment]
Hello,
it's new installation and folder is redmine_mail_reminder.

Konsole output
W dniu 08.07.2015 o 08:39, Androc pisze:
>
> Hello,
>
> is it a new installation or after an update ?
>
> If if is new, your plugin's directory should be redmine_mail_reminder
> and not mail_reminders.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hopebaytech/redmine_mail_reminder/issues/40#issuecomment-119456262>.
>

-- 
Michał Nowak
Administrator IT
Quality Of Service
phone +48 600 033 754
www.QoS.pl

**Comment by Androc** [comment]
Which branch of the plugin do you use ? Which version of redmine ?
Can you execute and post here the result of ruby scripts/info inside your redmine installation ?

**Comment by dondezo** [comment]
ruby bin/about

Environment:
  Redmine version                3.0.4.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                    
Redmine plugins:
  a_common_libs                  1.1.4
  hide_journal_details           0.0.1
  redmine_contacts               4.0.1
  redmine_contacts_helpdesk     
3.0.0                                                                                                                                                                            

  redmine_mail_reminder         
3.0.0.0001                                                                                                                                                                       

  redmine_mylyn_connector       
2.8.2.stable                                                                                                                                                                     

  redmine_wiki_extensions       
0.7.0                                                                                                                                                                            

  redmine_wktime                
1.8.1                                                                                                                                                                            

  scrum                         
0.11.1                                                                                                                                                                           

root@Redmine:/usr/share/redmine#                


W dniu 08.07.2015 o 09:28, Androc pisze:
>
> Which branch of the plugin do you use ? Which version of redmine ?
> Can you execute and post here the result of ruby scripts/info inside
> your redmine installation ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hopebaytech/redmine_mail_reminder/issues/40#issuecomment-119468368>.
>

-- 
Michał Nowak
Administrator IT
Quality Of Service
phone +48 600 033 754
www.QoS.pl

**Comment by Androc** [comment]
Unfortunately I don't own a Redmine 3.0 installation, so I can't test further.
But maybe your problem cames from the Redmine version or from a missing bundle.

Did you run bundle update when installing plugin ?
