### ISSUE TITLE
fail to install on redmine 2.6.5stable

### ISSUE THREAD

**Issue by landall** [jcppkkk/redmine_mail_reminder#74]
Install redmine using Bitname deploy version.

after run 
RAILS_ENV=production rake redmine:plugins:migrate

it reports
Could not find mini_portile-0.6.2 in any of the sources
Run `bundle install` to install missing gems.

hoever I installed it
 gem list mini_portile

**\* LOCAL GEMS ***
mini_portile (0.6.2, 0.6.0)
mini_portile2 (2.1.0)

what should i do?

**Comment by jcppkkk** [comment]
Currently support 3.2, 3.3 only
