### ISSUE TITLE
Mail does not reflect query results

### ISSUE THREAD

**Issue by dsgonzalezo** [jcppkkk/redmine_mail_reminder#94]
Hi @jcppkkk , I think this plugin is all I need but at the moment it is not working as expected.
I have created a query and it returns two issues that meet the condition for the same user, however the mail that is received only shows the first result.
I expected to be able to notify of all requests that met with a particular condition.
Tell me if I should do something in particular so that in the notofocación the total results of the query are included.

Thank you very much.

**Comment by jcppkkk** [comment]
@dsgonzalezo  have you check the user can view both issue? this reminder will send query result with each user's privilege; e.g. if a result issue is in a project that a user cannot visit, the the issue will not shows in the mail to the user.

**Comment by dsgonzalezo** [comment]
Thank you very much @jcppkkk and overcome the problem, now I have another situation, in my query I have grouped the results, however this is not showing me in the mail. Can you think if there is something to be done to solve it? thank you very much. Greetings. Diego

**Comment by jcppkkk** [comment]
grouped results can be a feature request. however it's not likely be implemented for the foreseeable future.
